### ISSUE TITLE
implement diff.py

### ISSUE THREAD

**Issue by maxxbw54** [SEEDGuard/SEEDUtils#3]
Compare two versions of dataset and return what are the changed data points.

**Tasks**
- [x] Add diff checker script for the SEEDPoisoner Component.
- [x] Provide sample input data for the `diffchecker_poisoner `script
- [x] Add diff checker script for the SEEDConsistencyChecker Component.
- [x] Provide sample input data for the `diffchecker_consistencychecker `script.

**Comment by nitesh31mishra** [comment]
SEEDConsistencyChecker data diff script commit - 6207bd5c372f1ec1259438a604c457de4b9e02aa
